/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2018-12-27 21:19:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class orderadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>个人信息管理</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<link href=\"Information.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"settled.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-sm navbar-dark bg-dark\">\r\n");
      out.write("      <a class=\"navbar-brand\">东方体育中心</a>\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarsExample03\" aria-controls=\"navbarsExample03\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      \t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarsExample03\">\r\n");
      out.write("        <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"Hello.jsp\">首页</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"news.jsp\">新闻 </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"rvnintro.jsp\">场馆介绍</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item dropdown\">\r\n");
      out.write("            <a class=\"nav-link dropdown-toggle active\" href=\"#\" id=\"dropdown03\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">场馆预约</a>\r\n");
      out.write("            <div class=\"dropdown-menu dropdown-top\" aria-labelledby=\"dropdown03\">\r\n");
      out.write("              <a class=\"dropdown-item dropdown-word\" href=\"reservation.jsp?rnvid=1\">篮球</a>\r\n");
      out.write("              <a class=\"dropdown-item dropdown-word\" href=\"reservation.jsp?rnvid=2\">乒乓球</a>\r\n");
      out.write("              <a class=\"dropdown-item dropdown-word\" href=\"reservation.jsp?rnvid=3\">羽毛球</a>\r\n");
      out.write("              <a class=\"dropdown-item dropdown-word\" href=\"reservation.jsp?rnvid=14\">排球</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"messageboard.jsp\">留言板</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item dropdown no-arrow\">\r\n");
      out.write("            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("            \t<i class=\"ps-icon\"></i>\r\n");
      out.write("            \t");
      out.print( session.getAttribute("usrName") );
      out.write("\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"dropdown-menu dropdown-menu-right dropdown-top\" aria-labelledby=\"userDropdown\">\r\n");
      out.write("              <a class=\"dropdown-item dropdown-word\" href=\"UserInform.jsp\">个人信息</a>\r\n");
      out.write("              <a class=\"dropdown-item dropdown-word\" href=\"myorder.jsp\">我的订单</a>\r\n");
      out.write("            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("              <a class=\"dropdown-item dropdown-word\" href=\"#\" data-toggle=\"modal\" data-target=\"#logoutModal\">登出</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\t<form class=\"personal-form\" id=\"order-form\" method=\"post\" action=\"OrderAdd\">\r\n");
      out.write("\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t<label for=\"ordName\">预约人姓名</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control form-signup\" id=\"ordName\" name=\"ordName\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t<label for=\"ordPhone\">手机</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control form-signup\" id=\"ordPhone\" name=\"ordPhone\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t<label for=\"rvnID\">场馆</label>\r\n");
      out.write("\t\t\t<input  type=\"text\" class=\"form-control form-signup\" id=\"rvnID\" name=\"rvnID\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t<label for=\"rvnRoom\">场地号</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control form-signup\" id=\"rvnRoom\" name=\"rvnRoom\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t<label for=\"ordPrice\">价格</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control form-signup\" id=\"ordPrice\" name=\"ordPrice\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t<label for=\"rvnDate\">日期</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control form-signup\" id=\"rvnDate\" name=\"rvnDate\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t<label for=\"rvnTime\" >时间段</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control form-signup\" id=\"rvnTime\" name=\"rvnTime\" readonly=\"readonly\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t<button class=\"btn btn-lg btn-primary btn-block btn-login\">预约下单</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("      <div class=\"container foot-text\">\r\n");
      out.write("        <span class=\"foot-t\">Created by Jiayi Zhu & Shen Lei</span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" style=\"display: none;\" aria-hidden=\"true\">\r\n");
      out.write("      <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("          <div class=\"modal-header\">\r\n");
      out.write("            <h5 class=\"modal-title\" id=\"exampleModalLabel\">确定登出？</h5>\r\n");
      out.write("            <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("              <span aria-hidden=\"true\">×</span>\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"modal-body\" style=\"text-align:center\">生命在于运动</div>\r\n");
      out.write("          <div class=\"modal-footer\">\r\n");
      out.write("            <button class=\"btn btn-secondary btn-cancel\" type=\"button\" data-dismiss=\"modal\">取消</button>\r\n");
      out.write("            <a class=\"btn btn-primary\" href=\"logout.jsp\">确定</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<script src=\"https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.staticfile.org/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
      out.write("\t<script src=\"bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\tvar room = ");
      out.print( request.getParameter("rvnRoom") );
      out.write(";\r\n");
      out.write("\t\tvar rvnRoom = document.getElementById(\"rvnRoom\");\r\n");
      out.write("\t\trvnRoom.value = \"场地\" + room;\r\n");
      out.write("\t\tvar id = ");
      out.print( request.getParameter("rvnId") );
      out.write(";\r\n");
      out.write("\t\tvar rvnID = document.getElementById(\"rvnID\");\r\n");
      out.write("\t\tif (id == 1) \r\n");
      out.write("\t\t\trvnID.value = \"篮球\";\r\n");
      out.write("\t\telse if (id == 2)\r\n");
      out.write("\t\t\trvnID.value = \"乒乓球\";\r\n");
      out.write("\t\telse if (id == 3)\r\n");
      out.write("\t\t\trvnID.value = \"羽毛球\";\r\n");
      out.write("\t\telse if (id == 4)\r\n");
      out.write("\t\t\trvnID.value = \"排球\";\r\n");
      out.write("\t\tvar time = ");
      out.print( request.getParameter("rvnTime") );
      out.write(";\r\n");
      out.write("\t\tvar rvnTime = document.getElementById(\"rvnTime\");\r\n");
      out.write("\t\trvnTime.value = (time+12) + \":00 - \" + (time+13) + \":00\";\r\n");
      out.write("\t\tvar rvnprice = ");
      out.print( request.getParameter("rvnPrice") );
      out.write(";\r\n");
      out.write("\t\tvar price = document.getElementById(\"ordPrice\");\r\n");
      out.write("\t\tprice.value = rvnprice;\r\n");
      out.write("\t\tvar rvnYear = ");
      out.print( request.getParameter("year") );
      out.write(";\r\n");
      out.write("\t\tvar rvnMonth = ");
      out.print( request.getParameter("month") );
      out.write(";\r\n");
      out.write("\t\tvar rvnDay = ");
      out.print( request.getParameter("day") );
      out.write(";\r\n");
      out.write("\t\tvar date = document.getElementById(\"rvnDate\");\r\n");
      out.write("\t\tdate.value = rvnYear+\"-\"+rvnMonth+\"-\"+rvnDay;\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
