/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2018-12-27 20:54:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rvnintro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>场馆介绍</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<link href=\"Hello.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"settled.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("\t<link href=\"news.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-sm navbar-dark bg-dark\">\r\n");
      out.write("      <a class=\"navbar-brand\">东方体育中心</a>\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarsExample03\" aria-controls=\"navbarsExample03\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      \t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarsExample03\">\r\n");
      out.write("        <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"Hello.jsp\">首页 <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"news.jsp\">新闻 </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item active\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"rvnintro.jsp\">场馆介绍</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item dropdown\">\r\n");
      out.write("            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"dropdown03\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">场馆预约</a>\r\n");
      out.write("            <div class=\"dropdown-menu dropdown-top\" aria-labelledby=\"dropdown03\">\r\n");
      out.write("              <a class=\"dropdown-item dropdown-word\" href=\"reservation.jsp?rnvid=1\">篮球</a>\r\n");
      out.write("              <a class=\"dropdown-item dropdown-word\" href=\"reservation.jsp?rnvid=2\">乒乓球</a>\r\n");
      out.write("              <a class=\"dropdown-item dropdown-word\" href=\"reservation.jsp?rnvid=3\">羽毛球</a>\r\n");
      out.write("              <a class=\"dropdown-item dropdown-word\" href=\"reservation.jsp?rnvid=4\">排球</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"messageboard.jsp\">留言板</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item dropdown no-arrow\">\r\n");
      out.write("            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("            \t<i class=\"ps-icon\"></i>\r\n");
      out.write("            \t");
      out.print( session.getAttribute("usrName") );
      out.write("\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"dropdown-menu dropdown-menu-right dropdown-top\" aria-labelledby=\"userDropdown\">\r\n");
      out.write("              <a class=\"dropdown-item dropdown-word\" href=\"UserInform.jsp\">个人信息</a>\r\n");
      out.write("              <a class=\"dropdown-item dropdown-word\" href=\"myorder.jsp\">我的订单</a>\r\n");
      out.write("            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("              <a class=\"dropdown-item dropdown-word\" href=\"#\" data-toggle=\"modal\" data-target=\"#logoutModal\">登出</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div id=\"ns\" class=\"center table-show col-lg-12\">\r\n");
      out.write("    \t<div class=\"center_tbl col-md-12\">\r\n");
      out.write("    \t\t<div class=\"card flex-md-row mb-4 box-shadow h-md-250\">\r\n");
      out.write("    \t\t\t<div class=\"card-body d-flex flex-column align-items-start\"> \r\n");
      out.write("    \t\t\t\t<h3 class=\"mb-0\">篮球馆</h3>\r\n");
      out.write("    \t\t\t\t<div class=\"mb-1 text-muted\">\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t<p class=\"card-text mb-auto\">\r\n");
      out.write("    \t\t\t\t\t2700平方米超大公共空间，净高11米，\r\n");
      out.write("\t\t\t\t\t\t无柱空间使展览功能发挥到最大；场馆顶部配有64盏防炫灯，\r\n");
      out.write("\t\t\t\t\t\t符合照度标准；地板采用比赛用全实木地板，常年维持25度的室内温度；\r\n");
      out.write("\t\t\t\t\t\t3个出入口，其中东门可出入小型车辆；2个安全出口，消防设备2组，保证基本安全需求\r\n");
      out.write("    \t\t\t\t</p>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<img class=\"card-img-right flex-auto d-none d-md-block\" data-src=\"holder.js/200x250?theme=thumb\" alt=\"Thumbnail [200x250]\" style=\"width: auto; height: 250px;\" src=\"images/lanqiu.jpg\" data-holder-rendered=\"true\">\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<div class=\"center_tbl col-md-12\">\r\n");
      out.write("    \t\t<div class=\"card flex-md-row mb-4 box-shadow h-md-250\">\r\n");
      out.write("    \t\t\t<div class=\"card-body d-flex flex-column align-items-start\"> \r\n");
      out.write("    \t\t\t\t<h3 class=\"mb-0\">乒乓球馆</h3>\r\n");
      out.write("    \t\t\t\t<div class=\"mb-1 text-muted\">\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t<p class=\"card-text mb-auto\">\r\n");
      out.write("    \t\t\t\t\t球馆创建于2009年夏。该馆地理位置优越，条件一流，\r\n");
      out.write("\t\t\t\t\t\t可承接各种规模的乒乓球比赛，并有强大的教练团队执教，常年招收各层次乒乓球学员。\r\n");
      out.write("\t\t\t\t\t\t球馆内打折出售各类乒乓球用品，球衣、球鞋、底板、套胶、\r\n");
      out.write("\t\t\t\t\t\t乒乓球桌等各类器械均低价出售，货真价实，并支持大量团购。\r\n");
      out.write("    \t\t\t\t</p>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<img class=\"card-img-right flex-auto d-none d-md-block\" data-src=\"holder.js/200x250?theme=thumb\" alt=\"Thumbnail [200x250]\" style=\"width: auto; height: 250px;\" src=\"images/pinpang.jpg\" data-holder-rendered=\"true\">\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<div class=\"center_tbl col-md-12\">\r\n");
      out.write("    \t\t<div class=\"card flex-md-row mb-4 box-shadow h-md-250\">\r\n");
      out.write("    \t\t\t<div class=\"card-body d-flex flex-column align-items-start\"> \r\n");
      out.write("    \t\t\t\t<h3 class=\"mb-0\">羽毛球馆 </h3>\r\n");
      out.write("    \t\t\t\t<div class=\"mb-1 text-muted\">\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t<p class=\"card-text mb-auto\">\r\n");
      out.write("    \t\t\t\t\t该球馆净高9米，设有16片塑胶羽毛球场地，球馆地面为双层龙骨加双层地板，\r\n");
      out.write("\t\t\t\t\t\t上铺专业地胶，增加了运动弹力。场地间隔1米，场地距离后墙休息区3米。\r\n");
      out.write("\t\t\t\t\t\t球馆内灯光设计是国际最新流行的侧面强烈柔和型的灯光，运动时防止了刺眼和眩光；\r\n");
      out.write("\t\t\t\t\t\t室内的墙壁为国际时尚的墨绿色，以减轻视觉疲劳。馆内配套有更衣室、淋浴室和卫生间。\r\n");
      out.write("    \t\t\t\t</p>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<img class=\"card-img-right flex-auto d-none d-md-block\" data-src=\"holder.js/200x250?theme=thumb\" alt=\"Thumbnail [200x250]\" style=\"width: auto; height: 250px;\" src=\"images/yumaoqiu.jpg\" data-holder-rendered=\"true\">\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<div class=\"center_tbl col-md-12\">\r\n");
      out.write("    \t\t<div class=\"card flex-md-row mb-4 box-shadow h-md-250\">\r\n");
      out.write("    \t\t\t<div class=\"card-body d-flex flex-column align-items-start\"> \r\n");
      out.write("    \t\t\t\t<h3 class=\"mb-0\">排球馆 </h3>\r\n");
      out.write("    \t\t\t\t<div class=\"mb-1 text-muted\">\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t<p class=\"card-text mb-auto\">\r\n");
      out.write("    \t\t\t\t\t排球场长度为18米，宽度为9米。四周至少有3米宽的无障碍区。\r\n");
      out.write("\t\t\t\t\t\t排球场地地面为塑胶场地。排球场地地面也有土质、水泥、沥青和木质等。\r\n");
      out.write("\t\t\t\t\t\t不论是采用木板地面还是合成材料地面，都必须保证运动员在比赛中不感到太滑或太粘，\r\n");
      out.write("\t\t\t\t\t\t并有一定的弹性。\r\n");
      out.write("    \t\t\t\t</p>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<img class=\"card-img-right flex-auto d-none d-md-block\" data-src=\"holder.js/200x250?theme=thumb\" alt=\"Thumbnail [200x250]\" style=\"width: auto; height: 250px;\" src=\"images/paiqiu.jpg\" data-holder-rendered=\"true\">\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t\r\n");
      out.write("    </div>\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("      <div class=\"container foot-text\">\r\n");
      out.write("        <span class=\"foot-t\">Created by Jiayi Zhu & Shen Lei</span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" style=\"display: none;\" aria-hidden=\"true\">\r\n");
      out.write("      <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("          <div class=\"modal-header\">\r\n");
      out.write("            <h5 class=\"modal-title\" id=\"exampleModalLabel\">确定登出？</h5>\r\n");
      out.write("            <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("              <span aria-hidden=\"true\">×</span>\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"modal-body\" style=\"text-align:center\">生命在于运动</div>\r\n");
      out.write("          <div class=\"modal-footer\">\r\n");
      out.write("            <button class=\"btn btn-secondary btn-cencel\" type=\"button\" data-dismiss=\"modal\">取消</button>\r\n");
      out.write("            <a class=\"btn btn-primary\" href=\"logout.jsp\">确定</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.staticfile.org/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
      out.write("\t<script src=\"bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
